from typing import Protocol


class AdapterStatus(Protocol):
    def configured(self) -> bool: ...
    def enabled(self) -> bool: ...
    def provider(self) -> str: ...
    def mode(self) -> str: ...
