from enum import Enum


class PhoenixState(str, Enum):
    INGESTED = "INGESTED"
    RECONNAISSANCE_COMPLETE = "RECONNAISSANCE_COMPLETE"
    EVIDENCE_COMPLETE = "EVIDENCE_COMPLETE"
    INTENT_RECONSTRUCTED = "INTENT_RECONSTRUCTED"
    MARKET_ANALYZED = "MARKET_ANALYZED"
    VALUE_DECISION = "VALUE_DECISION"
    PRODUCT_BLUEPRINT_COMPLETE = "PRODUCT_BLUEPRINT_COMPLETE"
    ENGINEERING_RESEARCH_COMPLETE = "ENGINEERING_RESEARCH_COMPLETE"
    IMPLEMENTATION_CONTRACT_READY = "IMPLEMENTATION_CONTRACT_READY"
    BUILDING = "BUILDING"
    VALIDATING = "VALIDATING"
    DIAGNOSING = "DIAGNOSING"
    REPAIRING = "REPAIRING"
    RESURRECTED = "RESURRECTED"
    NO_GO = "NO_GO"
    RESURRECTION_FAILED = "RESURRECTION_FAILED"


ALLOWED_TRANSITIONS: dict[PhoenixState, set[PhoenixState]] = {
    PhoenixState.INGESTED: {PhoenixState.RECONNAISSANCE_COMPLETE},
    PhoenixState.RECONNAISSANCE_COMPLETE: {PhoenixState.EVIDENCE_COMPLETE},
    PhoenixState.EVIDENCE_COMPLETE: {PhoenixState.INTENT_RECONSTRUCTED},
    PhoenixState.INTENT_RECONSTRUCTED: {PhoenixState.MARKET_ANALYZED},
    PhoenixState.MARKET_ANALYZED: {PhoenixState.VALUE_DECISION},
    PhoenixState.VALUE_DECISION: {
        PhoenixState.PRODUCT_BLUEPRINT_COMPLETE,
        PhoenixState.NO_GO,
    },
}


def can_transition(current: PhoenixState, nxt: PhoenixState) -> bool:
    return nxt in ALLOWED_TRANSITIONS.get(current, set())
